CREATE TABLE IF NOT EXISTS `charger_history` (
  `tagid` int(11) NOT NULL,
  `X` int(11) NOT NULL,
  `Y` int(11) NOT NULL,
  `T1` int(11) NOT NULL,
  `ForkLocation` int(11) NOT NULL,
  `LineT` int(11) NOT NULL,
  `AutoStatus` int(11) NOT NULL COMMENT 'Err:-1 Auto IDLE:1 手動:0 run:2',
  `Err` int(11) NOT NULL,
  `OUT_V` int(11) NOT NULL,
  `OUT_A` int(11) NOT NULL,
  `OUT_Watt` int(11) NOT NULL,
  `OUT_T` int(11) NOT NULL,
  `OUT_T2` int(11) NOT NULL,
  `OUT_mAh` int(11) NOT NULL,
  `OUT_Wh` int(11) NOT NULL,
  `steptime` varchar(30) NOT NULL,
  `totaltime` varchar(30) NOT NULL,
  `STEPIndex` int(11) NOT NULL,
  `IN_V` int(11) NOT NULL,
  `IN_A` int(11) NOT NULL,
  `IN_Watt` int(11) NOT NULL,
  `IN_kWh` int(11) NOT NULL,
  `IN_totaltime` int(11) NOT NULL,
  `cur_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `carno` int(11) NOT NULL,
  `VB1` int(11) NOT NULL,
  `IB1` int(11) NOT NULL,
  `BT1` int(11) NOT NULL,
  `VC1_MIN` int(11) NOT NULL,
  `VC1_MAX` int(11) NOT NULL,
  `BT1_2` int(11) NOT NULL,
  `SOC1` int(11) NOT NULL,
  `SOH1` int(11) NOT NULL,
  `PROT1` int(11) NOT NULL,
  `STAT1` int(11) NOT NULL,
  `CHG_AH1` int(11) NOT NULL,
  `DSG_AH1` int(11) NOT NULL,
  `CYCLE1` int(11) NOT NULL,
  `VB2` int(11) NOT NULL,
  `IB2` int(11) NOT NULL,
  `BT2` int(11) NOT NULL,
  `VC2_MIN` int(11) NOT NULL,
  `VC2_MAX` int(11) NOT NULL,
  `BT2_2` int(11) NOT NULL,
  `SOC2` int(11) NOT NULL,
  `SOH2` int(11) NOT NULL,
  `PROT2` int(11) NOT NULL,
  `STAT2` int(11) NOT NULL,
  `CHG_AH2` int(11) NOT NULL,
  `DSG_AH2` int(11) NOT NULL,
  `CYCLE2` int(11) NOT NULL,
  `bms1_fw` varchar(30) NOT NULL,
  `bms2_fw` varchar(30) NOT NULL,
  KEY `cur_time` (`cur_time`),
  KEY `bms1_fw` (`bms1_fw`),
  KEY `bms2_fw` (`bms2_fw`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
